apiVersion: v1
kind: Service
metadata:
  name: password-vault-manager
  labels:
    app: password-vault-manager
spec:
  type: ClusterIP
  selector:
    app: password-vault-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
